version: 0.0
os: linux

files:
  source: /
  destination: /home/ubuntu/riset_backend
permissions:
  - object: /home/ubuntu/riset_backend
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu