server:
  port: 80
spring:
  config:
    activate:
      on-profile: local
    import:
      - application-aws.yaml

  datasource:
    url: jdbc:mysql://localhost:${PORT}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${USERNAME}
    password: ${PASSWORD} # 로컬 mysql 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  datasource:
  #    url: jdbc:h2:mem:riset
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  packages-to-scan: com.github.riset_backend.web.controller
  api-docs:
    path: /api-docs



logging:
  config: classpath:logback-spring-local.xml