server:
  port: 8080
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  packages-to-scan: com.github.backend.web.controller
  api-docs:
    path: /api-docs

logging:
  config: classpath:logback-spring-prod.xml