springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match: /api/**


spring:
  datasource:
    # spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    # spring.datasource.url=jdbc:mysql://awseb-e-ppmxk3kkyd-stack-awsebrdsdatabase-enansim5fguk.cto0suya23gm.ap-northeast-2.rds.amazonaws.com/code_trails?useUnicode=true&characterEncoding=UTF-8
    # spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    # spring.jpa.hibernate.ddl-auto=create
    # spring.datasource.username=ebroot
    # spring.datasource.password=Wlstjd1597!

    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:Code_Trails
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: VmFhQ1RtU2tkbHN0a2ZrZGdveVJvcWtmd2tkYmFsqwecqwmgmbmbmflfsswerwqewqffa2323
    token:
      access-expiration-time: 30
      refresh-expiration-time: 60

  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.jinsung1017@gmail.com
    password: hwodhscokvcvehnt
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true


cloud:
  aws:
    s3:
      bucket: riset-dev-s3
    stack:
      auto: false
    credentials:
      access-key: '${IAM_ACCESS_KEY}'
      secret-key: '${IAM_SECRET_KEY}'
    region:
      static: ap-northeast-2

  servlet:
     multipart:
      max-file-size: 10MB
      max-request-size: 10MB