name: Java CI with Gradle

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["test2"]

env:
  PROJECT_NAME: riset_backend
  BUCKET_NAME: riset-bucket
  CODE_DEPLOY_APP_NAME: riset_project
  DEPLOYMENT_GROUP_NAME: riset_deploy_group

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build

      - name: Make Zip File
        run: zip -qq -t ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: actions/upload-artifact@v2
        with:
          aws-access-key-id: ${{ secrets.IAM_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.IAM_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment
                --application-name $CODE_DEPLOY_APP_NAME
                --deployment-config-name CodeDeployDefault.AllAtOnce
                --deployment-group-name $DEPLOYMENT_GROUP_NAME
                --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip

